name: CI
on:
  pull_request: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v4.2.2
      - name: Setup Python
        id: setup-python
        uses: quansight-labs/setup-python@v5.4.0
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install --no-cache-dir .
      - name: Run tests
        run: python -m pytest
